# f = open("textFile.txt", "r")
# print(f.readline())
# f.close()
f = open("textFile.txt", "w")
f.write("This is Amran from NSTU.")
f.close()
f = open("textFile.txt", "a")
f.write(" Address: 5th floor, Administrative building")
f.close()